### ISSUE TITLE
Is it still work in 2023?

### ISSUE THREAD

**Issue by phunlh2001** [baolhq/FECE#1]
I just found this repo, is it still working at the moment?

**Comment by baolhq** [comment]
Yes, but I'm too lazy to update fileID to corresponding files on Google Drive 🗿

**Comment by phunlh2001** [comment]
Ok. I've downloaded the SEB, a long time wait but I got it 😅

Thank you.

**Comment by phunlh2001** [comment]
Hi man, the SEB has just updated to a new version... and your tool does not work now 😥
